# Generated by Django 6.1.1 on 2026-09-18 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orientations', '0007_suivietape'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_probleme', models.CharField(choices=[('INFORMATION_INCORRECTE', 'Information incorrecte'), ('INFORMATION_INCOMPLETE', 'Information incomplète'), ('INFORMATION_OBSOLETE', 'Information obsolète'), ('AUTRE', 'Autre')], max_length=30, verbose_name='type de problème')),
                ('commentaire', models.TextField(max_length=1000, verbose_name='commentaire')),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours'), ('TRAITE', 'Traité')], default='NOUVEAU', max_length=20, verbose_name='statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('orientation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='orientations.orientationadministrative')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TraitementSignalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire_administrateur', models.TextField(max_length=1500, verbose_name='commentaire administrateur')),
                ('resultat', models.CharField(choices=[('RESOLU', 'Résolu'), ('NON_RESOLU', 'Non résolu'), ('REJETE', 'Rejeté')], max_length=20, verbose_name='résultat')),
                ('suite_a_donner', models.TextField(blank=True, max_length=1000, verbose_name='suite à donner')),
                ('date_traitement', models.DateTimeField(auto_now=True, verbose_name='date de traitement')),
                ('administrateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traitements_signalements', to=settings.AUTH_USER_MODEL)),
                ('signalement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traitement', to='signalements.signalement')),
            ],
        ),
    ]
