# Generated by Django 6.1.1 on 2026-09-08 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="nom de l'administration")),
                ('sigle', models.CharField(blank=True, max_length=50, verbose_name='sigle')),
                ('site_web', models.URLField(blank=True, verbose_name='site web')),
            ],
        ),
        migrations.CreateModel(
            name='DemarcheAdministrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255, verbose_name='intitulé')),
                ('description', models.TextField(verbose_name='description')),
                ('cout_indicatif', models.CharField(blank=True, max_length=100, verbose_name='coût indicatif')),
                ('delai_indicatif', models.CharField(blank=True, max_length=100, verbose_name='délai indicatif')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
            ],
        ),
        migrations.CreateModel(
            name='SourceAdministrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='titre')),
                ('url', models.URLField(verbose_name='URL de la source')),
                ('type', models.CharField(choices=[('API', 'API'), ('PAGE_WEB', 'Page web'), ('DOCUMENT', 'Document')], max_length=20, verbose_name='type de source')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('INDISPONIBLE', 'Indisponible'), ('A_VERIFIER', 'À vérifier')], default='DISPONIBLE', max_length=20, verbose_name='statut')),
                ('date_consultation', models.DateTimeField(blank=True, null=True, verbose_name='date de dernière consultation')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
            ],
        ),
        migrations.CreateModel(
            name='EtapeDemarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(verbose_name='ordre')),
                ('description', models.TextField(verbose_name='description')),
                ('demarche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='referentiel.demarcheadministrative')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='PieceRequise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name='libellé')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='obligatoire')),
                ('demarche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_requises', to='referentiel.demarcheadministrative')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='nom du service')),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='contact')),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='referentiel.administration')),
            ],
        ),
        migrations.AddField(
            model_name='demarcheadministrative',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='demarches', to='referentiel.serviceadministratif'),
        ),
    ]
