# Generated by Django 6.1.1 on 2026-09-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceadministrative',
            name='demarches',
            field=models.ManyToManyField(blank=True, related_name='sources', to='referentiel.demarcheadministrative'),
        ),
    ]
