# Generated by Django 6.1.1 on 2026-09-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0002_sourceadministrative_demarches'),
    ]

    operations = [
        migrations.AddField(
            model_name='demarcheadministrative',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='code de la démarche'),
        ),
    ]
