# Generated by Django 6.1.1 on 2026-09-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0003_demarcheadministrative_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demarcheadministrative',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='code de la démarche'),
        ),
    ]
