# Generated by Django 6.1.1 on 2026-09-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0004_alter_demarcheadministrative_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceadministrative',
            name='pays_application',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="pays d'application"),
        ),
    ]
