# Generated by Django 6.1.1 on 2026-09-26 00:16

from django.db import migrations


def set_source_countries(apps, schema_editor):
    """Associe les sources passeport à leur pays d'application."""

    SourceAdministrative = apps.get_model(
        "referentiel",
        "SourceAdministrative",
    )

    # Source utilisée pour une démarche effectuée au Sénégal.
    SourceAdministrative.objects.filter(
        titre="Passeport ordinaire - Ministère de l'Intérieur"
    ).update(
        pays_application="SN"
    )

    # Sources consulaires utilisées en France.
    SourceAdministrative.objects.filter(
        titre__icontains="Consulat général du Sénégal à Lyon"
    ).update(
        pays_application="FR"
    )

    SourceAdministrative.objects.filter(
        titre__icontains="Consulat général du Sénégal à Paris"
    ).update(
        pays_application="FR"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0005_sourceadministrative_pays_application'),
    ]

    operations = [
        migrations.RunPython(
            set_source_countries,
            migrations.RunPython.noop,
        ),
    ]