# Generated by Django 6.1.1 on 2026-10-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0006_set_source_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourceadministrative',
            name='pays_application',
        ),
    ]
