# Generated by Django 6.1.1 on 2026-10-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pays_residence',
        ),
    ]
