# Generated by Django 6.1.1 on 2026-09-08 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionComplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(verbose_name='texte de la question')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name="ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseComplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='contenu de la réponse')),
                ('date_reponse', models.DateTimeField(auto_now_add=True, verbose_name='date de réponse')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reponse', to='orientations.questioncomplementaire')),
            ],
        ),
        migrations.CreateModel(
            name='SituationAdministrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_initiale', models.TextField(verbose_name='description initiale')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questioncomplementaire',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='orientations.situationadministrative'),
        ),
        migrations.CreateModel(
            name='OrientationAdministrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.TextField(verbose_name="résumé de l'orientation")),
                ('avertissement', models.TextField(blank=True, verbose_name='avertissement')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='date de génération')),
                ('situation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orientation', to='orientations.situationadministrative')),
            ],
        ),
    ]
