# Generated by Django 6.1.1 on 2026-09-10 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientations', '0001_initial'),
        ('referentiel', '0002_sourceadministrative_demarches'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientationadministrative',
            name='demarche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orientations', to='referentiel.demarcheadministrative'),
        ),
        migrations.AddField(
            model_name='situationadministrative',
            name='public_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='identifiant public'),
        ),
    ]
