# Generated by Django 6.1.1 on 2026-09-10 10:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientations', '0002_orientationadministrative_demarche_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situationadministrative',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identifiant public'),
        ),
    ]
