# Generated by Django 6.1.1 on 2026-09-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientations', '0003_alter_situationadministrative_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncomplementaire',
            name='options',
            field=models.JSONField(blank=True, default=list, verbose_name='options de réponse'),
        ),
        migrations.AddField(
            model_name='questioncomplementaire',
            name='type_question',
            field=models.CharField(choices=[('TEXTE', 'Texte'), ('CHOIX_UNIQUE', 'Choix unique')], default='TEXTE', max_length=20, verbose_name='type de question'),
        ),
    ]
