# Generated by Django 6.1.1 on 2026-09-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientations', '0004_questioncomplementaire_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situationadministrative',
            name='description_initiale',
            field=models.TextField(max_length=2000, verbose_name='description initiale'),
        ),
    ]
