# Generated by Django 6.1.1 on 2026-09-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientations', '0005_alter_situationadministrative_description_initiale'),
    ]

    operations = [
        migrations.AddField(
            model_name='situationadministrative',
            name='pays_application',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="pays d'application"),
        ),
        migrations.AlterField(
            model_name='situationadministrative',
            name='description_initiale',
            field=models.TextField(max_length=1500, verbose_name='description initiale'),
        ),
    ]
