# Generated by Django 6.1.1 on 2026-09-15 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientations', '0006_situationadministrative_pays_application_and_more'),
        ('referentiel', '0004_alter_demarcheadministrative_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminee', models.BooleanField(default=False, verbose_name='étape terminée')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='referentiel.etapedemarche')),
                ('orientation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_etapes', to='orientations.orientationadministrative')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('orientation', 'etape'), name='unique_suivi_etape_orientation')],
            },
        ),
    ]
