# Generated by Django 6.1.1 on 2026-10-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orientations', '0008_situationadministrative_pays_residence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situationadministrative',
            name='pays_application',
        ),
        migrations.RemoveField(
            model_name='situationadministrative',
            name='pays_residence',
        ),
    ]
